color_bg0="#1a1b26"
color_bg1="#32344a"
color_bg2="#787c99"
color_fg0="#a9b1d6"
color_fg1="#e0af68"

color_status_fg="#7aa2f7"
color_status_bg="#32344a"

color_selected_fg="#c0caf5"
color_selected_bg="#7aa2f7"

color_highlight_fg="#9ece6a"
color_highlight_bg="#1a1b26"

color_current_fg="#f7768e"
color_current_bg="#1a1b26"

color_check_fg="#ad8ee6"

pane_border_fg="#a9b1d6"
pane_border_selected_fg="#9ece6a"

set -g @prefix_highlight_fg "${color_highlight_fg}"
set -g @prefix_highlight_bg "${color_highlight_bg}"
set -g @bg "${color_bg0}"

# Status bar settings
set -g status-style "bg=${color_bg0},fg=${color_fg0}"
set -g status "on"
set -g status-bg "${color_bg0}"
set -g status-justify "left"
#set -g status-left-length "100"
set -g status-right-length "100"

set -g window-style "fg=${color_fg0},bg=${color_bg1}"
set -g window-active-style "fg=${color_fg0},bg=${color_bg0}"

# Messages
set -g message-style "fg=${color_selected_fg},bg=${color_selected_bg}"
set -g message-command-style "fg=${color_selected_fg},bg=${color_selected_bg}"

# Panes
set -g pane-border-style "fg=${pane_border_fg}"
set -g pane-active-border-style "fg=${pane_border_selected_fg}"

# Windows
set -g window-status-activity-style "fg=${color_fg0},bg=${color_bg0},none"
set -g window-status-separator ""
set -g window-status-style "fg=${color_fg0},bg=${color_bg0},none"

# Statusline - current window
set -g window-status-current-format "#[fg=${color_current_fg},bg=${color_current_bg}]#I: #[fg=${color_check_fg},bg=${color_current_bg}](✓) #[fg=${color_current_fg},bg=${color_current_bg}]#W "

# Statusline - other windows
set -g window-status-format "#[fg=${color_highlight_fg},bg=${color_highlight_bg}]#I: #[fg=${color_fg0},bg=${color_highlight_bg}]#W "

# Statusline - right side
set -g status-right "#[fg=${color_fg1},bg=${color_bg0},nobold,nounderscore,noitalics]%Y-%m-%d %H:%M #[fg=${color_fg0},bg=${color_highlight_fg},nobold,nounderscore,noitalics] #[fg=${color_fg0},bg=${color_bg1}] #(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) #[fg=${color_fg0},bg=${color_current_fg},nobold,nounderscore,noitalics] #[fg=${color_fg0},bg=${color_bg1}] #S "

# Modes
set -g clock-mode-colour "${color_status_fg}"
set -g mode-style "fg=${color_highlight_fg} bg=${color_bg1} bold"

# Statusline - left side (empty)
set -g status-left ""

