[vars]
USER_FULLNAME = "Steve Beulac"
USER_EMAIL = "steve@beaulac.me"

[settings]
dotfiles.root = "{{config_root}}"
dotfiles.default_mode = "symlink"

[dotfiles]
"~/.config/mise/config.toml" = "config/mise/config.toml"
"~/.agents/AGENTS.md" = "config/agents/AGENTS.md"
"~/.pi" = { source = "config/pi", mode = "symlink-each" }
"~/.pi/agents/AGENTS.md" = "config/agents/AGENTS.md"
"~/.config/nvim/" = { source = "config/nvim", mode = "symlink-each" }
"~/.config/opencode" = { source = "config/opencode", mode = "symlink-each" }
"~/.config/fish/config.fish" = "config/fish/config.fish"
"~/.config/herdr/config.toml" = "config/herdr/config.toml"
"~/.config/git/config" = "config/git/config"
"~/.config/git/local" = { source = "templates/git.tmpl", mode = "template", template = "tera" }
"~/.bash_profile/mise" = { block = 'eval "$(mise activate bash)"' }
"~/.bash_profile/zoxide" = { block = 'eval "$(zoxide init bash)"' }
"~/.bash_profile/fzf" = { block = 'eval "$(fzf --bash)"' }
"~/.bash_aliases" = { source = "config/bash/aliases", mode = "symlink" }
"~/.config/zero/config.json" = { source = "config/zero", mode =  "copy" }

"~/.local/bin/tmux-open" = { source = "script/tmux-open", mode = "symlink" }
"~/.local/bin/ci" = { source = "script/ci", mode = "symlink" }
"~/.local/bin/n" = { source = "script/n", mode = "symlink" }
"~/.local/bin/git-bare-clone" = { source = "script/git-bare-clone", mode = "symlink" }
"~/.local/bin/ssh-auth" = { source = "script/ssh-auth", mode = "symlink" }

[bootstrap.mise_shell_activate] # mise activation in shell startup files
zprofile = "shims"
zshrc = "activate"

