[vars]
USER_FULLNAME = "Steve Beaulac"
USER_EMAIL = "steve@beaulac.me"
DOTFILES_DIR = "{{config_root}}"
SECOND_BRAIN = "~/Documents/sjb-brain"

[settings]
dotfiles.root = "{{config_root}}"
dotfiles.default_mode = "symlink"

[dotfiles]
"~/.config/btop" = "config/btop"
"~/.config/btop/themes/current.theme" = { source = "~/.config/omarchy/current/theme/btop.theme", mode = "symlink" }
"~/.config/mise/config.toml" = "config/mise/config.toml"
"~/.agents/AGENTS.md" = "config/agents/AGENTS.md"
"~/.pi" = { source = "config/pi", mode = "symlink-each" }
"~/.pi/agents/AGENTS.md" = "config/agents/AGENTS.md"
"~/.config/nvim/" = { source = "config/nvim", mode = "symlink-each" }
"~/.config/nvim/plugin/theme.lua" = { source = "~/.config/omarchy/current/theme/neovim-vimpack.lua", mode = "symlink" }
"~/.config/opencode" = { source = "config/opencode", mode = "symlink-each" }
"~/.config/fish" = { source = "config/fish", mode = "symlink-each" }
"~/.config/herdr/config.toml" = "config/herdr/config.toml"
"~/.config/git/config" = "config/git/config"
"~/.config/git/local" = { source = "templates/git.tmpl", mode = "template", template = "tera" }
"~/.bash_aliases" = { source = "config/bash/aliases", mode = "symlink" }
"~/.bashrc" = { source = "config/bash/profile", mode = "symlink" }
"~/.config/zero/config.json" = { source = "config/zero", mode =  "copy" }
"~/.config/worktrunk/config.toml" = { source = "config/worktrunk/config.toml", mode = "symlink" }
"~/.config/tmux/theme" = { source = "~/.config/omarchy/current/theme/tmux", mode = "symlink" }
"~/.config/tmux" = { source = "config/tmux", mode = "symlink-each" }
"~/.local/bin/tmux-open" = { source = "script/tmux-open", mode = "symlink" }
"~/.local/bin/ci" = { source = "script/ci", mode = "symlink" }
"~/.local/bin/n" = { source = "script/n", mode = "symlink" }
"~/.local/bin/s" = { source = "script/s", mode = "symlink" }
"~/.local/bin/t" = { source = "script/t", mode = "symlink" }
"~/.local/bin/git-bare-clone" = { source = "script/git-bare-clone", mode = "symlink" }
"~/.local/bin/ssh-auth" = { source = "script/ssh-auth", mode = "symlink" }
"~/.config/mise/env" = { source = "templates/dotenv.tmpl", mode = "template", template = "tera" }
"~/.local/bin/omarchy-theme-set" = { source = "script/omarchy-theme-set", mode = "symlink" }
"~/.local/bin/omarchy-theme-list" = { source = "script/omarchy-theme-list", mode = "symlink" }
"~/.local/bin/omarchy-hook" = { source = "script/omarchy-hook", mode = "symlink" }
"~/.local/bin/omarchy-theme-set-templates" = { source = "script/omarchy-theme-set-templates", mode = "symlink" }
"~/.local/bin/omarchy-restart-tmux" = { source = "script/omarchy-restart-tmux", mode = "symlink" }
"~/.local/bin/omarchy-restart-btop" = { source = "script/omarchy-restart-btop", mode = "symlink" }

[bootstrap.mise_shell_activate] # mise activation in shell startup files
zprofile = "shims"
zshrc = "activate"

[tasks.setup_shells]
description = "Script to setup some cli environment"
run = [
    'if [ -x /usr/bin/fish ]; then fish -c "fisher install franciscolourenco/done"; fi',
    'test -d ~/.config/tmux/plugins/tpm || git clone https://github.com/tmux-plugins/tpm  ~/.config/tmux/plugins/tpm',
    'tmux run-shell ~/.config/tmux/plugins/tpm/bindings/install_plugins',
]

[bootstrap.hooks.pre-packages]
run = "test -d ~/.config/omarchy/current/theme || rsync -av config/omarchy/default/ ~/.config/omarchy/current/theme/ --mkpath"

[tasks.bootstrap]
depends = ['setup_shells', 'setup_tmux', 'setup_pi', 'setup_herdr', 'setup_tmux', 'skills', 'dark']

