#!/bin/bash

# omarchy:summary=List available themes
# omarchy:examples=omarchy theme list | omarchy theme set "Tokyo Night"

{
  find ~/.config/omarchy/themes/ -mindepth 1 -maxdepth 1 \( -type d -o -type l \) -printf '%f\n'
  find "${DOTFILES_DIR}/themes/" -mindepth 1 -maxdepth 1 -type d -printf '%f\n'
} | sort -u | while read -r name; do
  echo "$name" | sed -E 's/(^|-)([a-z])/\1\u\2/g; s/-/ /g'
done
