[env]
USER_FULLNAME = "Steve Beulac"
USER_EMAIL = "steve@beaulac.me"

[settings]
experimental = true

[tools]
age = "latest"
"aqua:ogham/exa" = "latest"
bun = "latest"
clang = "latest"
codex = "latest"
copilot-cli = "latest"
croc = "latest"
fd = "latest"
"github:danielmiessler/fabric" = "latest"
"github:mrusme/reader" = "latest"
"github:ulyssa/iamb" = "latest"
"github:ZinoKader/portal" = "latest"
go = "latest"
herdr = "latest"
neovim = "latest"
node = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:mermaid-cli" = "latest"
"npm:pi-acp" = "latest"
opencode = "latest"
pi = "latest"
rg = "latest"
rust = "latest"
tree-sitter = "latest"
worktrunk = "latest"
