[env]
_.file = '~/.config/mise/env'

[settings]
experimental = true

[tools]
age = "latest"
"aqua:ogham/exa" = "latest"
bun = "latest"
clang = "latest"
codex = "latest"
copilot-cli = "latest"
croc = "latest"
fd = "latest"
"github:Gitlawb/zero" = "latest"
"github:danielmiessler/fabric" = "latest"
"github:mrusme/reader" = "latest"
"github:ulyssa/iamb" = "latest"
"github:ZinoKader/portal" = "latest"
go = "latest"
herdr = "latest"
neovim = "latest"
node = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:mermaid-cli" = "latest"
"npm:pi-acp" = "latest"
opencode = "latest"
pi = "latest"
rg = "latest"
zoxide = "latest"
fzf = "latest"
rust = "latest"
tree-sitter = "latest"
worktrunk = "latest"
jq = "latest"
tmux = "latest"

[tasks.setup_pi]
run = [
    'pi install npm:pi-lens',
    'pi install npm:pi-native-search',
    'pi install npm:@tintinweb/pi-subagents',
    'pi install npm:context-mode',
    'pi install npm:@gotgenes/pi-permission-system',
    'test -x /usr/bin/pass && /usr/bin/pass show config/pi/auth.json > ~/.pi/agent/auth.json'
]

[tasks.skills]
run = [
    'npx skills add SjB/skills',
    'npx skills add mattpocock/skills'	
]

[tasks.light]
run = [
    'ln -snf $DOTFILES_DIR/config/themes/nvim/light-theme.lua ~/.config/nvim/plugin/theme.lua',
    'ln -snf $DOTFILES_DIR/config/themes/tmux/light.theme ~/.config/tmux/theme',
    'tmux source-file ~/.config/tmux/tmux.conf && tmux refresh-client -S',
]

[tasks.dark]
run = [
    'ln -snf $DOTFILES_DIR/config/themes/nvim/dark-theme.lua ~/.config/nvim/plugin/theme.lua',
    'ln -snf $DOTFILES_DIR/config/themes/tmux/dark.theme ~/.config/tmux/theme',
    'tmux source-file ~/.config/tmux/tmux.conf && tmux refresh-client -S',
]
