[env]
_.file = '~/.config/mise/env'

[settings]
experimental = true

[tools]
age = "latest"
"aqua:ogham/exa" = "latest"
bun = "latest"
clang = "latest"
codex = "latest"
copilot-cli = "latest"
croc = "latest"
fd = "latest"
"github:Gitlawb/zero" = "latest"
"github:danielmiessler/fabric" = "latest"
"github:mrusme/reader" = "latest"
"github:ulyssa/iamb" = "latest"
"github:ZinoKader/portal" = "latest"
go = "latest"
herdr = "latest"
neovim = "latest"
node = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:mermaid-cli" = "latest"
"npm:pi-acp" = "latest"
opencode = "latest"
pi = "latest"
rg = "latest"
zoxide = "latest"
fzf = "latest"
rust = "latest"
tree-sitter = "latest"
worktrunk = "latest"
jq = "latest"
tmux = "latest"
eza = "latest"
dua = "latest"
bat = "latest"
"http:tea" = { 
    version = "0.15.1", 
    url = 'https://gitea.com/gitea/tea/releases/download/v{{ version }}/tea-{{ version }}-{{ os(macos="darwin", linux="linux") }}-{{ arch(x64="amd64", arm64="arm64") }}', 
    bin = "tea", 
    format = "raw" 
}

[tasks.setup_pi]
run = [
    'pi install npm:pi-lens',
    'pi install npm:pi-native-search',
    'pi install npm:@tintinweb/pi-subagents',
    'pi install npm:context-mode',
    'pi install npm:@ff-labs/pi-fff',
    'pi install npm:@dietrichgebert/ponytail',
    'pi install npm:@plannotator/pi-extension',
    'pi install npm:@gotgenes/pi-permission-system'
]

[tasks.skills]
run = [
    'npx skills add SjB/skills',
]

[tasks.herdr_setup]
run = [
    'herdr plugin install devashish2203/herdr-worktrunk --yes',
    'herdr plugin install qu8n/herdr-automatic-rename --yes',
    'herdr plugin install den-tanui/herdr-zoxide --yes',
    'herdr plugin install plannotator/herdr-annotate --yes',
]

[tasks.light]
run = [
    'ln -snf $DOTFILES_DIR/config/themes/nvim/light-theme.lua ~/.config/nvim/plugin/theme.lua',
    'ln -snf $DOTFILES_DIR/config/themes/tmux/light.theme ~/.config/tmux/theme',
    'if [ -n "$TMUX" ]; then tmux source-file ~/.config/tmux/tmux.conf && tmux refresh-client -S; fi',
]

[tasks.dark]
run = [
    'ln -snf $DOTFILES_DIR/config/themes/nvim/dark-theme.lua ~/.config/nvim/plugin/theme.lua',
    'ln -snf $DOTFILES_DIR/config/themes/tmux/dark.theme ~/.config/tmux/theme',
    'if [ -n "$TMUX" ]; then tmux source-file ~/.config/tmux/tmux.conf && tmux refresh-client -S; fi',
]
